export const teamLogoByName: Record<string, string> = {
  Alabama: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
  Arkansas: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
  Auburn: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
  Florida: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
  Georgia: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
  'Georgia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
  Kentucky: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
  LSU: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
  Mississippi: 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
  'Mississippi State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
  Missouri: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
  Oklahoma: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
  Sewanee: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Sewanee_Tigers_logo.svg/512px-Sewanee_Tigers_logo.svg.png',
  'South Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png',
  Tennessee: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
  Texas: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
  'Texas A&M': 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
  Tulane: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
  Vanderbilt: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
  Alabama: '/team-logos/Alabama.svg',
  Arkansas: '/team-logos/Arkansas.svg',
  Auburn: '/team-logos/Auburn.svg',
  Florida: '/team-logos/Florida.svg',
  Georgia: '/team-logos/Georgia.svg',
  'Georgia Tech': '/team-logos/Georgia Tech.svg',
  Kentucky: '/team-logos/Kentucky.svg',
  LSU: '/team-logos/LSU.svg',
  Mississippi: '/team-logos/Mississippi.svg',
  'Mississippi State': '/team-logos/Mississippi State.svg',
  Missouri: '/team-logos/Missouri.svg',
  Oklahoma: '/team-logos/Oklahoma.svg',
  Sewanee: '/team-logos/Sewanee.svg',
  'South Carolina': '/team-logos/South Carolina.svg',
  Tennessee: '/team-logos/Tennessee.svg',
  Texas: '/team-logos/Texas.svg',
  'Texas A&M': '/team-logos/Texas A&M.svg',
  Tulane: '/team-logos/Tulane.svg',
  Vanderbilt: '/team-logos/Vanderbilt.svg',
};

export function getTeamLogoPath(team?: string | null): string | null {
  if (!team) return null;
  return teamLogoByName[team] ?? null;
}
